global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 마이크로서비스 메트릭 수집
  - job_name: 'user-service'
    static_configs:
      - targets: ['localhost:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    
  - job_name: 'restaurant-service'
    static_configs:
      - targets: ['localhost:8002']
    metrics_path: '/metrics'
    scrape_interval: 15s
    
  - job_name: 'order-service'
    static_configs:
      - targets: ['localhost:8003']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # 시스템 모니터링 (선택사항)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    
  # tempo 연동
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

remote_write:
  - url: "http://loki:3100/loki/api/v1/push" 