global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    
  - job_name: 'sample-micro-app'
    static_configs:
      - targets: ['host.docker.internal:8080']
    
  # 서비스 추가 시 아래에 작성

  # tempo 연동
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

remote_write:
  - url: "http://loki:3100/loki/api/v1/push" 